// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: todo_image.proto

package go_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTodoPhotoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//The request can be the PhotoInfo or the bytes data for the image
	//
	// Types that are assignable to Request:
	//	*AddTodoPhotoRequest_Info
	//	*AddTodoPhotoRequest_Data
	Request isAddTodoPhotoRequest_Request `protobuf_oneof:"request"`
}

func (x *AddTodoPhotoRequest) Reset() {
	*x = AddTodoPhotoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_image_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTodoPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTodoPhotoRequest) ProtoMessage() {}

func (x *AddTodoPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_image_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTodoPhotoRequest.ProtoReflect.Descriptor instead.
func (*AddTodoPhotoRequest) Descriptor() ([]byte, []int) {
	return file_todo_image_proto_rawDescGZIP(), []int{0}
}

func (m *AddTodoPhotoRequest) GetRequest() isAddTodoPhotoRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *AddTodoPhotoRequest) GetInfo() *AddTodoPhotoRequest_PhotoInfo {
	if x, ok := x.GetRequest().(*AddTodoPhotoRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *AddTodoPhotoRequest) GetData() []byte {
	if x, ok := x.GetRequest().(*AddTodoPhotoRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isAddTodoPhotoRequest_Request interface {
	isAddTodoPhotoRequest_Request()
}

type AddTodoPhotoRequest_Info struct {
	Info *AddTodoPhotoRequest_PhotoInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type AddTodoPhotoRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*AddTodoPhotoRequest_Info) isAddTodoPhotoRequest_Request() {}

func (*AddTodoPhotoRequest_Data) isAddTodoPhotoRequest_Request() {}

type AddTodoPhotoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Size    uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *AddTodoPhotoResponse) Reset() {
	*x = AddTodoPhotoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_image_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTodoPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTodoPhotoResponse) ProtoMessage() {}

func (x *AddTodoPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_image_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTodoPhotoResponse.ProtoReflect.Descriptor instead.
func (*AddTodoPhotoResponse) Descriptor() ([]byte, []int) {
	return file_todo_image_proto_rawDescGZIP(), []int{1}
}

func (x *AddTodoPhotoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddTodoPhotoResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AddTodoPhotoRequest_PhotoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TodoId string `protobuf:"bytes,1,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
}

func (x *AddTodoPhotoRequest_PhotoInfo) Reset() {
	*x = AddTodoPhotoRequest_PhotoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_image_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTodoPhotoRequest_PhotoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTodoPhotoRequest_PhotoInfo) ProtoMessage() {}

func (x *AddTodoPhotoRequest_PhotoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_image_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTodoPhotoRequest_PhotoInfo.ProtoReflect.Descriptor instead.
func (*AddTodoPhotoRequest_PhotoInfo) Descriptor() ([]byte, []int) {
	return file_todo_image_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AddTodoPhotoRequest_PhotoInfo) GetTodoId() string {
	if x != nil {
		return x.TodoId
	}
	return ""
}

var File_todo_image_proto protoreflect.FileDescriptor

var file_todo_image_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x6f, 0x64, 0x6f, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x13, 0x41, 0x64, 0x64,
	0x54, 0x6f, 0x64, 0x6f, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x39, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x49,
	0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x24, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x6f, 0x64, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x6f, 0x64, 0x6f, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x44, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x50, 0x68, 0x6f,
	0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6b, 0x70, 0x61, 0x6c, 0x61, 0x43, 0x68, 0x69,
	0x64, 0x69, 0x65, 0x62, 0x65, 0x72, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b,
	0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todo_image_proto_rawDescOnce sync.Once
	file_todo_image_proto_rawDescData = file_todo_image_proto_rawDesc
)

func file_todo_image_proto_rawDescGZIP() []byte {
	file_todo_image_proto_rawDescOnce.Do(func() {
		file_todo_image_proto_rawDescData = protoimpl.X.CompressGZIP(file_todo_image_proto_rawDescData)
	})
	return file_todo_image_proto_rawDescData
}

var file_todo_image_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_todo_image_proto_goTypes = []interface{}{
	(*AddTodoPhotoRequest)(nil),           // 0: todo.AddTodoPhotoRequest
	(*AddTodoPhotoResponse)(nil),          // 1: todo.AddTodoPhotoResponse
	(*AddTodoPhotoRequest_PhotoInfo)(nil), // 2: todo.AddTodoPhotoRequest.PhotoInfo
}
var file_todo_image_proto_depIdxs = []int32{
	2, // 0: todo.AddTodoPhotoRequest.info:type_name -> todo.AddTodoPhotoRequest.PhotoInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_todo_image_proto_init() }
func file_todo_image_proto_init() {
	if File_todo_image_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todo_image_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTodoPhotoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_image_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTodoPhotoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_image_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTodoPhotoRequest_PhotoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_todo_image_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AddTodoPhotoRequest_Info)(nil),
		(*AddTodoPhotoRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todo_image_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_image_proto_goTypes,
		DependencyIndexes: file_todo_image_proto_depIdxs,
		MessageInfos:      file_todo_image_proto_msgTypes,
	}.Build()
	File_todo_image_proto = out.File
	file_todo_image_proto_rawDesc = nil
	file_todo_image_proto_goTypes = nil
	file_todo_image_proto_depIdxs = nil
}
